### ISSUE TITLE
In blending editor, enabled means disabled

### ISSUE THREAD

**Issue by mmnosek** [Starcounter/Blending#145] opened 2018-03-22 15:34 UTC
The label on the screenshot below should be "Disabled". Checking checkbox means actually that condition is disabled.

![blendingeditor](https://user-images.githubusercontent.com/4943949/37780346-e52ffd46-2dee-11e8-882e-66f7514ed674.png)

**Comment by kegor** [comment] 2018-03-23 09:21
For me it also looked like a bug, it's good that now we have a confirmed work item for this.

**Comment by kegor** [comment] 2018-03-28 10:12
Closed because the fix was merged in the #150.

**Closed by kegor** 2018-03-28 10:12 UTC
Labels: BlendingEditor, bug
