### ISSUE TITLE
Failling TC tests

### ISSUE THREAD

**Issue by ubbeK** [Starcounter/Blending#308] opened 2018-10-12 09:46 UTC
https://teamcity.starcounter.org/viewLog.html?buildId=72148&tab=buildResultsDiv&buildTypeId=Apps_Blending_BlendingMasterWithStarcounterDevelop24 (built it 3 times in a row, same result)

Failing tests
```
LayoutGroupsPageTest(Chrome).LayoutGroupsPage_AddLayout
LayoutGroupsPageTest(Firefox).LayoutGroupsPage_AddLayout
```

@warpech @kegor I do not know who to assign.

**Comment by warpech** [comment] 2018-10-26 09:56
Closing as a duplicate of https://github.com/Starcounter/Blending/issues/287

**Closed by warpech** 2018-10-26 09:56 UTC
