### ISSUE TITLE
Compositions are not imported for already existing layouts

### ISSUE THREAD

**Issue by warpech** [Starcounter/Blending#288] opened 2018-09-18 12:36 UTC
### Steps to reproduce

1. Import a file with layouts and custom compositions
2. Go to `/blendingeditor/settings` and Delete all compositions
3. Import the same file again

### Expected result

The compositions from this file should be imported

### Actual result

The compositions from this are not imported.

The compositions are imported correctly only if you Delete both: layouts and compositions.

**Comment by PatrykSzwer** [comment] 2018-09-18 13:37
I investigated this issue and turns out: "It's not a bug, It's a feature".

Reason why ur composition is disappearing is not because of the composition itself but because of layouts, It's conditions and ordering feature working.

When you run blending app you will have automatically generated layouts with rules: TopbarLayout and LoginLayout. The first one has `Catch all` rule.
![image](https://user-images.githubusercontent.com/25042256/45690961-d979ff00-bb57-11e8-89aa-78c05fae7cae.png)

When you import json file for Omni solution, you will have situation like this:
![image](https://user-images.githubusercontent.com/25042256/45691097-2bbb2000-bb58-11e8-9b2d-dbb0f44c4dcf.png)

Most important part are those 2 rules:
![image](https://user-images.githubusercontent.com/25042256/45691271-92403e00-bb58-11e8-9127-4bbd5759a012.png)

As you can see here, Topbar rule is above BackOffice rule, so it will override it. Before, when you clicked `Delete all compositions` you deleted composition for Topbar rule, so you won't see it. If you simply put rules in correct order (and in my case, remove header rule for host `backoffice.`) you will see backoffice composition correctly loaded.

Closing this, since It's not a bug.

**Closed by PatrykSzwer** 2018-09-18 13:37 UTC
Labels: BlendingEditor, bug
