### ISSUE TITLE
⏰ Many tests don't pass

### ISSUE THREAD

**Issue by un-tone** [Starcounter/Blending#25] opened 2018-01-08 14:28 UTC
I didn't find an issue about that so I'm creating the new one.

Also, TeamCity doesn't run tests.

### Steps to reproduce

1. Build Blending solution
2. Run `test.bat`

### Expected result

All tests pass.

### Actual result

Many errors.

### Screenshot

Composition tests:
![image](https://user-images.githubusercontent.com/1625378/34674855-8b56672c-f498-11e7-83fd-6d6934f1982a.png)

Blending tests:

![image](https://user-images.githubusercontent.com/1625378/34674877-9a97cb40-f498-11e7-8ba1-33e90c8cf9d0.png)

**Comment by warpech** [comment] 2018-01-08 21:53
Last time I checked, all of the tests were passing in Chrome. Maybe you can try that? `--test.bat params="Browsers=Chrome"`

**Comment by warpech** [comment] 2018-01-09 05:58
The tests that fail in Firefox due to `InternalError: Too much recursion` seem to be caused by https://github.com/mozilla/geckodriver/issues/904.

Solution: change the helper function in Selenium to not return an element (`return arguments[0].shadowRoot`). The helper function should return only primitive values like string, number, boolean.

@PatrykSzwer can you take this?

**Comment by warpech** [comment] 2018-01-09 05:58
The tests that fail in Firefox due to `InternalError: Too much recursion` seem to be caused by https://github.com/mozilla/geckodriver/issues/904.

Solution: change the helper function in Selenium to not return an element (`return arguments[0].shadowRoot`). The helper function should return only primitive values like string, number, boolean.

KitchenSink is also affected by this.

@PatrykSzwer can you take this?

cc @alshakero

**Comment by PatrykSzwer** [comment] 2018-01-09 13:15
I've made PR fixing `Too much recursion` in Kitchensink: https://github.com/Starcounter/KitchenSink/pull/223. After acceptation, I'll apply referenced solution for Blending app.

**Comment by warpech** [comment] 2018-01-15 16:53
Closing as done in https://github.com/Starcounter/Blending/pull/33

**Closed by warpech** 2018-01-15 16:53 UTC

**Comment by warpech** [comment] 2018-01-21 20:54
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/Blending/releases/tag/5.2.0
- published in the App Warehouse
