### ISSUE TITLE
Solution builds with warnings

### ISSUE THREAD

**Issue by warpech** [Starcounter/Blending#41] opened 2018-01-12 12:05 UTC
The solution builds with few deprecation warnings. @kegor could you please look up what are the current methods to use and upgrade the code?

**Comment by kegor** [comment] 2018-01-14 19:29
Some additional details:
If I'm building Blending with SC 2.4 installed I see last warning:
![error_sc24](https://user-images.githubusercontent.com/17431807/34919813-fc55f704-f979-11e7-9461-a1148fb40095.PNG)
Meantime references for Authorization looks not properly loaded:
![authorization_sc24](https://user-images.githubusercontent.com/17431807/34919834-14551f74-f97a-11e7-974f-53aeb385e211.PNG)
In other hand if I'm trying to build Blending with SC 2.3 installed I see errors about wrong SC version:
![error_sc23](https://user-images.githubusercontent.com/17431807/34919847-36b52ab4-f97a-11e7-85c7-de53338a106c.PNG)
And ok references in Authorization:
![authorization_sc23](https://user-images.githubusercontent.com/17431807/34919851-4707451e-f97a-11e7-8b7f-f433d010432e.PNG)

**Comment by PatrykSzwer** [comment] 2018-01-15 09:06
You can't build Blending app with SC 2.3.1. It supports only SC 2.4.0 by design.

**Comment by warpech** [comment] 2018-01-15 12:21
It will not work to build Building with Starcounter 2.3.x. We should only focus on Starcounter 2.4.

@PatrykSzwer, @joozek78 is this normal that we get the following warning in Blending with Starcounter 2.4? What should we do about it?

![image](https://user-images.githubusercontent.com/566463/34942188-f2ae8428-f9f6-11e7-8c9e-64cf28dc7f79.png)

**Comment by joozek78** [comment] 2018-01-15 13:29
This warning is true and is (currently, unfortunately) expected.

1. Part of Authorization library contains some database code
   1. This part is not always used, it's the "permissions in database" feature
   1. This part will not work in 2.4, because it has not been weaved 
   1. If it had been weaved, it would not work in 2.3
1. We could split the Authorization library into "core" - which works everywhere, "permissions in database for 2.3" and "permissions in database for 2.4"
   1. That solution would cover all SC versions, but the warning would probably persist. "Core" of Authorization still references SC, but doesn't need weaving. Maybe @per-samuelsson knows how to disable this warning in this case
1. We could just put weaved assemblies of Authorization on nuget, essentially ending 2.3 support
1. We could do nothing and not use "permissions in database" in 2.4. AFAIK we don't use them

**Comment by per-samuelsson** [comment] 2018-01-15 14:06
> Maybe @per-samuelsson knows how to disable this warning in this case.

Not how to disable it, no. Its emitted by us. Maybe we need some way to disable that warning actually, I never thought of that.

I guess the only fast thing I can come up with is to make sure the referenced library is ran through the weaver. Even if there would be no database classes, it would be "tagged" as weaved, and the warning would disappear.

**Comment by per-samuelsson** [comment] 2018-01-15 14:09
And FWIW: why I emit that warning in the first place is to make sure 2.4 projects are properly set up. Remember: in 2.3 projects are *not* weaved as part of building, and in 2.4 they **have to be** (or rather: have to be, for database classes to be detected properly). 

I'm afraid that if we just do nothing instead of emitting that warning, we'll see issues coming in saying that things don't work as expected when apps are started (i.e. classes aren't considered database classes, etc).

**Comment by warpech** [comment] 2018-01-15 14:17
Is there a way to mark this warning as acknowledged?

Perhaps we should then document this warning in the Docs then? cc @Mackiovello 

Closing the issue as solved in https://github.com/Starcounter/Blending/pull/46

**Comment by warpech** [comment] 2018-01-15 14:18
> I guess the only fast thing I can come up with is to make sure the referenced library is ran through the weaver. Even if there would be no database classes, it would be "tagged" as weaved, and the warning would disappear.

@kegor can you try doing that?

A good project hygiene suggests that the app should build without warnings.

Perhaps we should at least document the warning in the Docs? cc @Mackiovello 

Closing the issue as solved in https://github.com/Starcounter/Blending/pull/46

**Comment by per-samuelsson** [comment] 2018-01-16 09:04
> Perhaps we should at least document the warning and the workaround proposed by Per in the Docs? 

I'd suggest we wait with that. Remember, this is Odessa, a version we are not releasing sharp for yet some time. So instead, I'd say that now that we know about this problem (one I didn't think of before), we raise an issue and schedule it, and see if we can improve on the experience.

> > I guess the only fast thing I can come up with is to make sure the referenced library is ran through the weaver. Even if there would be no database classes, it would be "tagged" as weaved, and the warning would disappear.
> 
> @kegor can you try doing that? A good project hygiene suggests that the app should build without warnings.

To do that, you need to weave it compile-time, as the referencing project expect. There is a mismatch going on here, in terms of our projects: blending is configured and built targeting **2.4**, while the referenced library is still on **2.3**. Fixing that mismatch will fix the issue. Why? Because (again), in **2.4** we have switched to compile-time weaving. In 2.3, weaving take place only when bootstrapping.

**Comment by warpech** [comment] 2018-01-17 16:50
> There is a mismatch going on here, in terms of our projects: blending is configured and built targeting 2.4, while the referenced library is still on 2.3. Fixing that mismatch will fix the issue.

@joozek78 could you please release a version of the Authorization library for Starcounter 2.4?

**Comment by kegor** [comment] 2018-02-07 11:40
@warpech, yes, I can confirm that if last warning mentioned above already tracked in another work item (#54) than we can close this one.

**Closed by kegor** 2018-02-07 11:40 UTC
